PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>


##
# banner Every class, object property and data property must have an SKOS definition.


SELECT DISTINCT ?warning ?resource
WHERE
{
  ?resource rdf:type ?type.
  VALUES ?type {owl:Class owl:ObjectProperty owl:DatatypeProperty}
  FILTER NOT EXISTS {?resource skos:definition ?definition. }
  
  FILTER REGEX(STR(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)
  
  BIND (CONCAT("PRODERROR: Resource ", STR(?resource), " does not have a SKOS definition.") as ?warning)
}
