PREFIX owl:   <http://www.w3.org/2002/07/owl#> 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX afn:   <http://jena.apache.org/ARQ/function#>


##
# banner An individual's name should be in the Upper Camel Case.


SELECT DISTINCT ?warning ?individual
WHERE 
{
  ?individual a owl:NamedIndividual .
  FILTER (!(regex(afn:localname(?individual), "([A-Z][a-z0-9\\-_]+)+")))

  FILTER regex(str(?resource), <HYGIENE_TESTS_FILTER_PARAMETER>)	

  BIND (CONCAT("WARN: Name of individual ", STR(?individual), " may not be in the Upper Camel Case.") AS ?warning)
}
